/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.store;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Souvik
 */
public class SearchMedicine extends javax.swing.JFrame {

    /**
     * Creates new form SearchMedicine
     */
    public SearchMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineSearch = new javax.swing.JTextField();
        nameSearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SEARCH MEDICINE MODULE");

        medicineSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineSearchActionPerformed(evt);
            }
        });
        medicineSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                medicineSearchKeyPressed(evt);
            }
        });

        nameSearchButton.setText("SEARCH");
        nameSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicineSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(nameSearchButton)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(medicineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(nameSearchButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicineSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineSearchActionPerformed

    private void nameSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchButtonActionPerformed
        // TODO add your handling code here:
        String med= medicineSearch.getText().replace("!", "!!")
                                            .replace("%", "!%")
                                            .replace("_", "!_")
                                            .replace("[", "![");
    
        String str1="SELECT * FROM inventory WHERE productid=? OR name LIKE ? ESCAPE '!' ";
        try
        {
        Connection con=DBConnection.getConnection();
        PreparedStatement ps=con.prepareStatement(str1);
        ps.setString(1, med);
        ps.setString(2, "%" + med + "%");
        ResultSet i=ps.executeQuery();
            if(i.next())
            {
                ImageIcon icon = new ImageIcon("right.png");
                JOptionPane.showMessageDialog(rootPane, i.getString("name") + "\n" + "Quantity Available :" + i.getInt("quantity"), "Message",HEIGHT, icon);
            }
            else
            {
                ImageIcon icon1 = new ImageIcon("wrong.png");
                JOptionPane.showMessageDialog(rootPane, "PRODUCT NOT FOUND", "Message", HEIGHT, icon1);

            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_nameSearchButtonActionPerformed

    private void medicineSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicineSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        String med= medicineSearch.getText().replace("!", "!!")
                                            .replace("%", "!%")
                                            .replace("_", "!_")
                                            .replace("[", "![");
    
        String str1="SELECT * FROM inventory WHERE productid=? OR name LIKE ? ESCAPE '!' ";
        try
        {
        Connection con=DBConnection.getConnection();
        PreparedStatement ps=con.prepareStatement(str1);
        ps.setString(1, med);
        ps.setString(2, "%" + med + "%");
        ResultSet i=ps.executeQuery();
            if(i.next())
            {
                ImageIcon icon = new ImageIcon("right.png");
                JOptionPane.showMessageDialog(rootPane, i.getString("name") + "\n" + "Quantity Available :" + i.getInt("quantity"), "Message",HEIGHT, icon);
            }
            else
            {
                ImageIcon icon1 = new ImageIcon("wrong.png");
                JOptionPane.showMessageDialog(rootPane, "PRODUCT NOT FOUND", "Message", HEIGHT, icon1);

            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_medicineSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField medicineSearch;
    private javax.swing.JButton nameSearchButton;
    // End of variables declaration//GEN-END:variables
}
